kind = "web"
previewPath = "/"
title = "طلبات اوفرلك"
version = "1.0.0"
id = "artifacts/food-order"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 23357

[services.development]
run = "pnpm --filter @workspace/food-order run dev"

[services.env]
PORT = "23357"
BASE_PATH = "/"
