import { db } from "@workspace/db";
import {
  categoriesTable,
  restaurantsTable,
  menuItemsTable,
} from "@workspace/db";

async function seed() {
  console.log("🌱 Seeding database...");

  await db.delete(menuItemsTable);
  await db.delete(restaurantsTable);
  await db.delete(categoriesTable);

  const categories = await db
    .insert(categoriesTable)
    .values([
      { name: "Grills", nameAr: "مشاوي", icon: "🔥", imageUrl: "" },
      { name: "Burgers", nameAr: "برغر", icon: "🍔", imageUrl: "" },
      { name: "Pizza", nameAr: "بيتزا", icon: "🍕", imageUrl: "" },
      { name: "Chicken", nameAr: "دجاج", icon: "🍗", imageUrl: "" },
      { name: "Vegetables & Fruits", nameAr: "خضروات وفواكه", icon: "🥗", imageUrl: "" },
      { name: "Sweets", nameAr: "حلويات", icon: "🍰", imageUrl: "" },
      { name: "Drinks", nameAr: "مشروبات", icon: "🧃", imageUrl: "" },
      { name: "Shawarma", nameAr: "شاورما", icon: "🌯", imageUrl: "" },
    ])
    .returning();

  console.log(`✅ ${categories.length} categories inserted`);

  const restaurants = await db
    .insert(restaurantsTable)
    .values([
      {
        name: "Pizza Napoli",
        nameAr: "بيتزا نابولي",
        description: "Authentic Italian pizza",
        descriptionAr: "بيتزا إيطالية أصيلة",
        category: "Pizza",
        categoryAr: "بيتزا",
        rating: 4.5,
        deliveryTime: "20-30 د",
        deliveryMinutes: 25,
        minOrder: 4000,
        imageUrl: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&q=80",
        isOpen: true,
        isFreeDelivery: true,
        discountPercent: 15,
        phone: "",
        whatsapp: "9647001234567",
        address: "تكريت",
      },
      {
        name: "Al-Bait Al-Shami",
        nameAr: "مطعم البيت الشامي",
        description: "Best grills in Salah al-Din",
        descriptionAr: "أفضل مشاوي في صلاح الدين",
        category: "Grills",
        categoryAr: "مشاوي",
        rating: 4.7,
        deliveryTime: "25-35 د",
        deliveryMinutes: 30,
        minOrder: 5000,
        imageUrl: "https://images.unsplash.com/photo-1544025162-d76694265947?w=600&q=80",
        isOpen: true,
        isFreeDelivery: false,
        discountPercent: 20,
        phone: "",
        whatsapp: "9647001234568",
        address: "تكريت",
      },
      {
        name: "Golden Chicken",
        nameAr: "الدجاج الذهبي",
        description: "Crispy fried chicken",
        descriptionAr: "دجاج مقلي مقرمش",
        category: "Chicken",
        categoryAr: "دجاج",
        rating: 4.6,
        deliveryTime: "15-25 د",
        deliveryMinutes: 18,
        minOrder: 3500,
        imageUrl: "https://images.unsplash.com/photo-1562967914-608f82629710?w=600&q=80",
        isOpen: true,
        isFreeDelivery: true,
        discountPercent: 0,
        phone: "",
        whatsapp: "9647001234569",
        address: "سامراء",
      },
      {
        name: "Burger Palace",
        nameAr: "برغر بالاس",
        description: "American-style burgers",
        descriptionAr: "برغر على الطريقة الأمريكية",
        category: "Burgers",
        categoryAr: "برغر",
        rating: 4.3,
        deliveryTime: "20-30 د",
        deliveryMinutes: 22,
        minOrder: 4500,
        imageUrl: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&q=80",
        isOpen: true,
        isFreeDelivery: false,
        discountPercent: 10,
        phone: "",
        whatsapp: "9647001234570",
        address: "بيجي",
      },
      {
        name: "Shawarma King",
        nameAr: "شاورما كينج",
        description: "Best shawarma in town",
        descriptionAr: "أشهى شاورما في المدينة",
        category: "Shawarma",
        categoryAr: "شاورما",
        rating: 4.8,
        deliveryTime: "10-20 د",
        deliveryMinutes: 15,
        minOrder: 3000,
        imageUrl: "https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=600&q=80",
        isOpen: true,
        isFreeDelivery: true,
        discountPercent: 0,
        phone: "",
        whatsapp: "9647001234571",
        address: "تكريت",
      },
      {
        name: "Sweet Dreams",
        nameAr: "سويت دريمز",
        description: "Arabic and western desserts",
        descriptionAr: "حلويات عربية وغربية",
        category: "Sweets",
        categoryAr: "حلويات",
        rating: 4.4,
        deliveryTime: "20-35 د",
        deliveryMinutes: 28,
        minOrder: 3000,
        imageUrl: "https://images.unsplash.com/photo-1551024601-bec78aea704b?w=600&q=80",
        isOpen: false,
        isFreeDelivery: false,
        discountPercent: 25,
        phone: "",
        whatsapp: "9647001234572",
        address: "الدور",
      },
    ])
    .returning();

  console.log(`✅ ${restaurants.length} restaurants inserted`);

  const restMap = Object.fromEntries(restaurants.map((r) => [r.nameAr, r.id]));

  const menuItems = await db
    .insert(menuItemsTable)
    .values([
      // بيتزا نابولي
      {
        restaurantId: restMap["بيتزا نابولي"],
        name: "Margherita Pizza",
        nameAr: "بيتزا مارغريتا",
        descriptionAr: "طماطم، موزاريلا، ريحان طازج",
        description: "Tomato, mozzarella, basil",
        price: 8000,
        imageUrl: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400&q=80",
        category: "Pizza",
        categoryAr: "بيتزا",
        isAvailable: true,
      },
      {
        restaurantId: restMap["بيتزا نابولي"],
        name: "Pepperoni Pizza",
        nameAr: "بيتزا بيبروني",
        descriptionAr: "بيبروني، موزاريلا، صلصة الطماطم",
        description: "Pepperoni, mozzarella, tomato sauce",
        price: 10000,
        imageUrl: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400&q=80",
        category: "Pizza",
        categoryAr: "بيتزا",
        isAvailable: true,
      },
      {
        restaurantId: restMap["بيتزا نابولي"],
        name: "Four Cheese Pizza",
        nameAr: "بيتزا أربعة أجبان",
        descriptionAr: "موزاريلا، شيدر، بارميزان، غودا",
        description: "Mozzarella, cheddar, parmesan, gouda",
        price: 12000,
        imageUrl: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=400&q=80",
        category: "Pizza",
        categoryAr: "بيتزا",
        isAvailable: true,
      },
      // البيت الشامي
      {
        restaurantId: restMap["مطعم البيت الشامي"],
        name: "Mixed Grill",
        nameAr: "مشاوي مشكل",
        descriptionAr: "تشكيلة من الكباب والتكة والدجاج المشوي",
        description: "Assorted kebabs, tikka, grilled chicken",
        price: 18000,
        imageUrl: "https://images.unsplash.com/photo-1544025162-d76694265947?w=400&q=80",
        category: "Grills",
        categoryAr: "مشاوي",
        isAvailable: true,
      },
      {
        restaurantId: restMap["مطعم البيت الشامي"],
        name: "Lamb Kebab",
        nameAr: "كباب لحم غنم",
        descriptionAr: "كباب طازج على الفحم مع الخبز العربي",
        description: "Fresh lamb kebab on charcoal with Arabic bread",
        price: 14000,
        imageUrl: "https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=400&q=80",
        category: "Grills",
        categoryAr: "مشاوي",
        isAvailable: true,
      },
      {
        restaurantId: restMap["مطعم البيت الشامي"],
        name: "Grilled Chicken",
        nameAr: "دجاج مشوي كامل",
        descriptionAr: "دجاج طازج مشوي على الفحم مع السلطة",
        description: "Whole grilled chicken on charcoal",
        price: 12000,
        imageUrl: "https://images.unsplash.com/photo-1598103442097-8b74394b95c3?w=400&q=80",
        category: "Grills",
        categoryAr: "مشاوي",
        isAvailable: true,
      },
      // الدجاج الذهبي
      {
        restaurantId: restMap["الدجاج الذهبي"],
        name: "Crispy Chicken Meal",
        nameAr: "وجبة دجاج مقرمش",
        descriptionAr: "قطعتان دجاج + بطاطا + مشروب",
        description: "2 crispy chicken pieces + fries + drink",
        price: 7500,
        imageUrl: "https://images.unsplash.com/photo-1562967914-608f82629710?w=400&q=80",
        category: "Chicken",
        categoryAr: "دجاج",
        isAvailable: true,
      },
      {
        restaurantId: restMap["الدجاج الذهبي"],
        name: "Chicken Strips",
        nameAr: "شرائح دجاج",
        descriptionAr: "شرائح دجاج مقرمشة مع صوص",
        description: "Crispy chicken strips with dipping sauce",
        price: 6000,
        imageUrl: "https://images.unsplash.com/photo-1567620832903-9fc6debc209f?w=400&q=80",
        category: "Chicken",
        categoryAr: "دجاج",
        isAvailable: true,
      },
      {
        restaurantId: restMap["الدجاج الذهبي"],
        name: "Family Bucket",
        nameAr: "دلو العائلة",
        descriptionAr: "12 قطعة دجاج + 2 بطاطا كبيرة + 4 مشروبات",
        description: "12 pieces + 2 large fries + 4 drinks",
        price: 22000,
        imageUrl: "https://images.unsplash.com/photo-1626645738196-c2a7c87a8f58?w=400&q=80",
        category: "Chicken",
        categoryAr: "دجاج",
        isAvailable: true,
      },
      // برغر بالاس
      {
        restaurantId: restMap["برغر بالاس"],
        name: "Classic Burger",
        nameAr: "برغر كلاسيك",
        descriptionAr: "لحم بقري، خس، طماطم، جبن، صوص خاص",
        description: "Beef patty, lettuce, tomato, cheese, special sauce",
        price: 6000,
        imageUrl: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&q=80",
        category: "Burgers",
        categoryAr: "برغر",
        isAvailable: true,
      },
      {
        restaurantId: restMap["برغر بالاس"],
        name: "Double Smash Burger",
        nameAr: "برغر دبل سماش",
        descriptionAr: "لحمتان مسطحتان، جبن مذاب، مخلل، بصل كرامل",
        description: "Double smash patties, melted cheese, pickles, caramelized onion",
        price: 9000,
        imageUrl: "https://images.unsplash.com/photo-1553979459-d2229ba7433b?w=400&q=80",
        category: "Burgers",
        categoryAr: "برغر",
        isAvailable: true,
      },
      // شاورما كينج
      {
        restaurantId: restMap["شاورما كينج"],
        name: "Chicken Shawarma",
        nameAr: "شاورما دجاج",
        descriptionAr: "شاورما دجاج مع الثوم وطرشي",
        description: "Chicken shawarma with garlic sauce and pickles",
        price: 4000,
        imageUrl: "https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=400&q=80",
        category: "Shawarma",
        categoryAr: "شاورما",
        isAvailable: true,
      },
      {
        restaurantId: restMap["شاورما كينج"],
        name: "Meat Shawarma",
        nameAr: "شاورما لحم",
        descriptionAr: "شاورما لحم مع الطحينة والبقدونس",
        description: "Meat shawarma with tahini and parsley",
        price: 5000,
        imageUrl: "https://images.unsplash.com/photo-1494390248081-4e521a5940db?w=400&q=80",
        category: "Shawarma",
        categoryAr: "شاورما",
        isAvailable: true,
      },
      {
        restaurantId: restMap["شاورما كينج"],
        name: "Shawarma Plate",
        nameAr: "طبق شاورما",
        descriptionAr: "شاورما مشكلة مع أرز وسلطة",
        description: "Mixed shawarma with rice and salad",
        price: 9500,
        imageUrl: "https://images.unsplash.com/photo-1432139555190-58524dae6a55?w=400&q=80",
        category: "Shawarma",
        categoryAr: "شاورما",
        isAvailable: true,
      },
      // سويت دريمز
      {
        restaurantId: restMap["سويت دريمز"],
        name: "Kunafa",
        nameAr: "كنافة بالجبن",
        descriptionAr: "كنافة بالجبن مع القطر",
        description: "Cheese kunafa with sugar syrup",
        price: 5000,
        imageUrl: "https://images.unsplash.com/photo-1579697096985-41fe1430e5df?w=400&q=80",
        category: "Sweets",
        categoryAr: "حلويات",
        isAvailable: true,
      },
      {
        restaurantId: restMap["سويت دريمز"],
        name: "Tiramisu",
        nameAr: "تيراميسو",
        descriptionAr: "تيراميسو إيطالي أصيل",
        description: "Authentic Italian tiramisu",
        price: 6000,
        imageUrl: "https://images.unsplash.com/photo-1551024601-bec78aea704b?w=400&q=80",
        category: "Sweets",
        categoryAr: "حلويات",
        isAvailable: true,
      },
      {
        restaurantId: restMap["سويت دريمز"],
        name: "Chocolate Cake",
        nameAr: "كيكة الشوكولاتة",
        descriptionAr: "كيكة شوكولاتة بلجيكية غنية",
        description: "Rich Belgian chocolate cake",
        price: 7000,
        imageUrl: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400&q=80",
        category: "Sweets",
        categoryAr: "حلويات",
        isAvailable: true,
      },
    ])
    .returning();

  console.log(`✅ ${menuItems.length} menu items inserted`);
  console.log("🎉 Seed complete!");
  process.exit(0);
}

seed().catch((err) => {
  console.error("❌ Seed failed:", err);
  process.exit(1);
});
